## Device settings, provide one of the following:
port: '/dev/imu'

publisher_queue_size: 5

#frame_id: "imu_link"
# Message publishers
pub_imu: true
pub_quaternion: true
pub_mag: true
pub_angular_velocity: true
pub_acceleration: true
pub_free_acceleration: true
pub_dq: true
pub_dv: true
pub_sampletime: true
pub_temperature: true
pub_pressure: true
pub_gnss: false
pub_twist: false
pub_transform: true
pub_positionLLA: true
pub_velocity: false
