obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.45, -0.3], [-0.45, 0.3], [0.20, 0.3], [0.20, -0.3]] # Robot Size

min_obstacle_height:  0
max_obstacle_height:  0.6

inflation_radius: 0.5
cost_scaling_factor: 3.0

map_type: voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  0.6
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             20
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 3.0
  raytrace_range: 3.5
  publish_voxel_map: false
  observation_sources: scan
  scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.55  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

