DWAPlannerROS:

  acc_lim_theta: 3.2
  acc_lim_trans: 0.55
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  angular_sim_granularity: 0.1
  controller_frequency: 20.0
  forward_point_distance: 0.2
  global_frame_id: map


  goal_distance_bias: 20.0
  latch_xy_goal_tolerance: false
  max_scaling_factor: 0.2
  max_vel_theta: 1.75
  max_vel_trans: 0.4
  max_vel_x: 0.4
  max_vel_y: 0.0
  min_vel_theta: 0.2
  min_vel_trans: 0.11
  min_vel_x: 0.0

  min_vel_y: 0.0

  occdist_scale: 0.02

  oscillation_reset_angle: 0.2


  oscillation_reset_dist: 0.05

  path_distance_bias: 40.0

  prune_plan: false

  publish_cost_grid_pc: true


  publish_traj_pc: true

  restore_defaults: false

  scaling_speed: 0.25

  sim_granularity: 0.025


  sim_time: 1.5

  stop_time_buffer: 0.2

  theta_stopped_vel: 0.1

  trans_stopped_vel: 0.01


  twirling_scale: 0.0

  use_dwa: true

  vth_samples: 20

  vx_samples: 6

  vy_samples: 1


  xy_goal_tolerance: 0.2

  yaw_goal_tolerance: 20
